services:
  db:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/01-ddl.sql:/docker-entrypoint-initdb.d/01-ddl.sql
      - ./db/02-indexes.sql:/docker-entrypoint-initdb.d/02-indexes.sql
      - ./db/03-views.sql:/docker-entrypoint-initdb.d/03-views.sql
      - ./db/04-data.sql:/docker-entrypoint-initdb.d/04-data.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5555:5432"

  backend:
    build: ./backend
    env_file: .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pgdata: